# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

repo_url: https://github.com/wdpm/get-started-mkdocs
repo_name: wdpm/get-started-mkdocs
# https://github.com/wdpm/get-started-mkdocs/edit/main/docs/index.md
edit_uri: edit/main/docs/

site_name: Markdown Docs
site_url: http://example.com
nav:
  - home:
      - index.md
      - tags: tags.md
  - setup:
      #      - setup/index.md
      - get-started: setup/get-started.md
      - user-guide: setup/user-guide.md
      - theme: setup/theme.md
  - mkdocs-material:
      - setup: mkdocs-material/setup.md
      - reference: mkdocs-material/reference.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
# admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
# buttons
  - attr_list
# code block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
#  content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wdpm
      name: wdpm on GitHub
  version:
    provider: mike
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
      custom: Custom cookie
    actions:
      - accept
      - manage
      - reject

extra_javascript:
  - javascripts/consent.js
  - javascripts/shortcuts.js

copyright: >
  Copyright &copy; 2016 - 2022 Martin Donath –
  <a href="#__consent">Change cookie settings</a>

plugins:
  # https://www.mkdocs.org/user-guide/configuration/#environment-variables
  - social:
      cards: !ENV [ CARDS, false ]
      cards_color:
        fill: "#0FF1CE"
        text: "#FFFFFF"
      cards_font: Noto Sans SC
  - search:
      #      separator: '[\s\u200b\-]'
      separator: '[\s\-\.]'
      lang:
        - ja
        - en
  - tags:
      tags_file: tags.md
      # Warning: ('tags_slugify', 'Unrecognised configuration name: tags_slugify')
      #      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #        kwds:
      #          case: lower
      # Warning: ('tags_slugify_separator', 'Unrecognised configuration name: tags_slugify_separator')
  #      tags_slugify_separator: "-"
  - git-revision-date-localized:
      enabled: !ENV [ CI, false ]
      enable_creation_date: true
      type: date
      fallback_to_build_date: true


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    admonition:
      #      github icons
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    edit: material/file-edit-outline # material/file-edit
    repo: fontawesome/brands/git-alt
    logo: bootstrap/3-circle-fill
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
  features:
    - content.tabs.link
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    #    - navigation.tracking
    - navigation.tabs
    #    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - markdown
    - md
    - bash
    - yml
    - yaml
    - rust